### ISSUE TITLE
Create a baseline estimator using XGboost and logistic regression

### ISSUE THREAD

**Issue by tkpratardan** [kaizen-ai/kaizenflow#1028]
Create a baseline estimator:
 - XGbosst
 - Logistic Regression

**Comment by gpsaggese** [comment]
Epic + estimate pls

More specs pls.
I don't see how we can remove the independence assumption of the two team goals and it's not clear how to use a non-parametric model. In practice, the choices are like logistic / multinomial / Poisson regression, which IMO are likely very similar.

Happy to explore but let's have a clear plan.

PS: I bet that 1) Poisson can't be beaten and 2) performance actually improves by making the model more constrained (like using team ranking and then do a panel regression instead of learning team by team).
ML from the books != ML that works in the real world.

**Comment by sonaalKant** [comment]
Closing, this is done and merged in https://github.com/kaizen-ai/kaizenflow/pull/1049
