### ISSUE TITLE
Unit test `normalize()`

### ISSUE THREAD

**Issue by DanilYachmenev** [kaizen-ai/kaizenflow#785]
There is a `normalize()` in `core/signal_processing/misc_transformations.py` ([link](https://github.com/sorrentum/sorrentum/blob/b2038a09192848d50da5b015dd1ecb6705883d18/core/signal_processing/misc_transformations.py#L232)) that is being used in the lib

We need to add unit tests using synthetic test data. Create simple short input signal that is Series. Run the function on it and compare the outcome with string signature (for ref see tests in `amp/helpers/test/test_hpandas.py` e.g. `Test_merge_dfs1`)

See [unit test doc](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style

Assigning @samarth9008 to re-distribute

FYI @gpsaggese

**Comment by SrujanaKomaravolu** [comment]
Hi,

I just wanted to confirm if you would like me to proceed with the task of writing unit tests for the `normalize()` function. Please let me know your preference regarding this task.

Thank you,
Srujana

**Comment by DanilYachmenev** [comment]
> I just wanted to confirm if you would like me to proceed with the task of writing unit tests for the `normalize()` function. Please let me know your preference regarding this task.

Yes
do as requested in the issue desc

add 2 unit tests:
1) simple signal
2) signal with NaN value (should assert)

create simple artificial signal for each test method and simply run function on it
please use reference code mentioned in the task

remember that here we check rather how you follow the guidelines than your code skill, the task should be basic

**Comment by SrujanaKomaravolu** [comment]
Hi ,

I have gone through the source code , which is in  core/signal_processing/misc_transformations.py and I have been assigned a task to write unit test for normalize ().
I would like to know where do I have to add code, for example, here (in the comment box) or do I have permissions to directly update code in the folder?

Kindly help me in this issue.

Thanks,
Srujana

**Comment by samarth9008** [comment]
Only if you read the docs carefully, you would have realized how to contribute and what file does this code goes into

**Comment by SrujanaKomaravolu** [comment]
okay

**Comment by SrujanaKomaravolu** [comment]
Hello Team,

I wanted to inform you that I'm currently in the midst of my final semester exams, which has caused a delay in completing the assigned task. I've begun reviewing the documents again and have started working on the task. However, due to the final projects and assignments, I anticipate that the submission may be delayed.

I apologize for any inconvenience this may cause and assure you that after this week, I will dedicate all my time to this project. I kindly request your understanding and support during this time.

Thank you,
Srujana

**Comment by samarth9008** [comment]
@aish-nidhi 

One last task for you.

@SrujanaKomaravolu 

Let us know when you are back we will assign a different task

**Comment by SrujanaKomaravolu** [comment]
Ok, I will let you know.

**Comment by aish-nidhi** [comment]
I could not get to this task as I was busy with something personal since Thursday evening and over the weekend.
Will try to complete this asap.
Apologies for the delay.

**Comment by samarth9008** [comment]
Closing as merged

**Comment by SrujanaKomaravolu** [comment]
Hi,
I am writing to inform you that I have successfully completed my exams and am now fully available to contribute to our project. I am eager to dedicate my time and skills to the project's success and am prepared to commit myself wholeheartedly to our collective efforts.

I am requesting the team to allocate me task, which I couldn't complete unfortunately because of my finals.

Thank you for your understanding and support.

Best regards,
Srujana
