### ISSUE TITLE
On-board Neha Pathak

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#840]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old) 
  - [x] **Read [How to organize your work](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md)**
  - [x] **Read [Quick start for developing](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md)**
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works and read about our docker methodology
  - [x] **Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully** 
     - OK if some are failing while running it
  - [x] **Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)**
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] **Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)**
  - [x] **How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)**
  - [x]  If you are graduating soon and you would like to get a full-time job in
  one of the companies in the KaizenFlow ecosystem reach out to GP at
  gp@kaizen-tech.io

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant  @gpsaggese

**Comment by neha2801-create** [comment]
Hey Samarth,

Good afternoon!

Thanks again for this detailed mail will go through these links.

Have a wonderful rest of your day!

Regards
Neha Pathak

From: Samarth KaPatel ***@***.***>
Sent: Monday, April 22, 2024 8:31 AM
To: kaizen-ai/kaizenflow ***@***.***>
Cc: neha2801-create ***@***.***>; Assign ***@***.***>
Subject: [kaizen-ai/kaizenflow] On-board Neha Pathak (Issue #840)


Please follow this checklist. Post any errors you face in this issue.

  *   [ ] Acknowledge the pledge to put time in the project here<https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old>
  *   [ ] Read How to organize your work<https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md>
  *   [ ] Read Quick start for developing<https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md>
  *   [ ] Make sure the Docker dev container<https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md> works and read about our docker methodology
  *   [ ] Make sure the unit tests<https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md> run successfully
     *   OK if some are failing while running it
  *   [ ] Read Sorrentum Python coding style guide<https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md>
  *   [ ] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  *   [ ] Get assigned a warm-up issue
  *   [ ] Learn about the Morning Email<https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email>
  *   [ ] How to do a review<https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md>
  *   [ ] If you are graduating soon and you would like to get a full-time job in
one of the companies in the KaizenFlow ecosystem reach out to GP at
***@***.******@***.***>

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant<https://github.com/sonaalKant> @gpsaggese<https://github.com/gpsaggese>

**Comment by samarth9008** [comment]
Pls use Github GUI for conversation. With mail it adds unwanted info.

**Comment by neha2801-create** [comment]
Clicking on Link:
At page:
https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#read-python-style-guide
Link is : Python Style Guide: it doesn't open proper page
![image](https://github.com/kaizen-ai/kaizenflow/assets/77967216/88a2a085-9618-4f9c-898d-7313d46d5998)
![image](https://github.com/kaizen-ai/kaizenflow/assets/77967216/dcf4b41a-7fb5-481a-b148-43c8d4832524)

Kindly let me know the alternative link if any.

**Comment by samarth9008** [comment]
Good job finding it

It should be this link - https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md

Can you create a PR with this correction?

**Comment by neha2801-create** [comment]
Thanks @samarth9008,
May I know what steps should i follow for this PR?

**Comment by samarth9008** [comment]
https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md#writing-and-contributing-code

**Comment by neha2801-create** [comment]
May I raise this PR after 6 pm, since currently I am not working. I will rejoin post 6 pm.

**Comment by samarth9008** [comment]
No worries take your time

**Comment by neha2801-create** [comment]
Hi @samarth9008 ,
I have completed all required tasks. Now can you assign me the warm of issue.
Thanks!

**Comment by samarth9008** [comment]
Assigned

https://github.com/kaizen-ai/kaizenflow/issues/786

**Comment by samarth9008** [comment]
Closing as done
