### ISSUE TITLE
On-board Nittesh Kumar

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#890]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old) 
  - [x] **Read [How to organize your work](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md)**
  - [x] **Read [Quick start for developing](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md)**
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works and read about our docker methodology
  - [x] **Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully** 
     - OK if some are failing while running it
  - [x] **Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)**
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] **Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)**
  - [x] **How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)**
  - [x]  If you are graduating soon and you would like to get a full-time job in
  one of the companies in the KaizenFlow ecosystem reach out to GP at
  gp@kaizen-tech.io

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant  @gpsaggese

**Comment by Nitesh703** [comment]
Hello @samarth9008  & @sonaalKant ,
I'm building the thin environment, when I run the command "source dev_scripts/client_setup/build.sh" to setup, 
<img width="1278" alt="Screenshot 2024-04-30 at 7 04 19 PM" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/5713feeb-0d42-449b-b626-a618730c69f3">
I get the error mentioned in the screenshot. But, at the same time venv is also getting created in my src folder, which indicates that environment is setup. So, should I ignore the error message in screenshot?

**Comment by Nitesh703** [comment]
<img width="1280" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/d929e94a-0780-4ea2-8d62-dd48d27b1d6a">
also, when I try to activate the environment. The output is not exactly the same as output mentioned in the document. But, it says SUCCESS as the end.

**Comment by samarth9008** [comment]
For the first one

Try uncommenting line 11 in this file and do it again

https://github.com/kaizen-ai/kaizenflow/blob/master/dev_scripts/client_setup/requirements.txt


For the second one

What shell you are using? We only support bash. If you are using zsh please switch to bash

**Comment by Nitesh703** [comment]
@samarth9008  
Earlier I was using zsh, & now I switched to bash. 
1. I uncommented line 11 & executed "source dev_scripts/client_setup/build.sh" command again. Didn't get any error. 
2. after executing 'source dev_scripts/setenv_amp.sh' output still doesn't match with output in the documentation. 
<img width="622" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/b8c68fa9-4870-4192-9bda-669901c69853">

**Comment by samarth9008** [comment]
This is correct

**Comment by Nitesh703** [comment]
I was able to start the docker container by executing **'i docker_bash'**, but when I try to start jupter server using command **'i docker_jupyter'**, it says i command not found.
<img width="1009" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/8e2fc4f2-be97-4b67-a180-f221a527393f">

**Comment by samarth9008** [comment]
All the `i *`  should be run from outside the container

**Comment by Nitesh703** [comment]
Got it. I've jupyter notebook started in my browser & currently I'm at the Linter. I'm a bit confused about what do I have to do in Linter part?

**Comment by gpsaggese** [comment]
The linter is used to clean up your code before submitting a PR.

**Comment by Nitesh703** [comment]
Hello @samarth9008  
can we setup a 5 minute call, I have few questions regarding Docker dev container?

**Comment by samarth9008** [comment]
@Sameep2808 Can you take care of this?

**Comment by samarth9008** [comment]
> Hello @samarth9008 can we setup a 5 minute call, I have few questions regarding Docker dev container?

Also you do no need to msg twice. Discussing technical issues on GH is the way we follow

**Comment by Sameep2808** [comment]
> Hello @samarth9008 can we setup a 5 minute call, I have few questions regarding Docker dev container?

Hey @Nitesh703 can you post all your questions here first.

**Comment by Nitesh703** [comment]
@Sameep2808 
[[ > sudo /bin/bash -c "(source /venv/bin/activate; pip install yfinance)"
     > python -c "import finance"  ]] 
when I run these commands to test a package in a Docker container It says no such file or directory,
<img width="1276" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/1c0c3019-ee08-4e16-b622-14a2d64771f7">
<img width="804" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/474f29fe-0d0a-4e14-92bf-f24be8bf52af">

**Comment by Nitesh703** [comment]
@Sameep2808 

`i docker_build_local_image --version 1.0.0` 
`i docker_build_local_image --version 1.0.0 --no-cache`
when I execute these commands, it's throwing an assertion error. 


`(amp.client_venv) (base) Nitteshs-MacBook-Air:kaizenflow1 nitteshkataria$ i docker_build_local_image --version 1.0.0 --no-cache
INFO: > cmd='/Users/nitteshkataria/src/venv/amp.client_venv/bin/invoke docker_build_local_image --version 1.0.0 --no-cache'
## docker_build_local_image: 
Traceback (most recent call last):
  File "/Users/nitteshkataria/src/venv/amp.client_venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/Users/nitteshkataria/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/Users/nitteshkataria/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/Users/nitteshkataria/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/nitteshkataria/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/nitteshkataria/src/kaizenflow1/helpers/lib_tasks_docker_release.py", line 105, in docker_build_local_image
    hlitadoc._dassert_is_subsequent_version(
  File "/Users/nitteshkataria/src/kaizenflow1/helpers/lib_tasks_docker.py", line 860, in _dassert_is_subsequent_version
    hdbg.dassert_lte(current_version, version)
  File "/Users/nitteshkataria/src/kaizenflow1/helpers/hdbg.py", line 229, in dassert_lte
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/Users/nitteshkataria/src/kaizenflow1/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/Users/nitteshkataria/src/kaizenflow1/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
1.14.0 <= 1.0.0
################################################################################`

**Comment by gpsaggese** [comment]
> @Sameep2808 [[ > sudo /bin/bash -c "(source /venv/bin/activate; pip install yfinance)" > python -c "import finance" ]] when I run these commands to test a package in a Docker container It says no such file or directory

You are not inside a Docker container, you are installing as root on your laptop
Also it's telling you that `activate` didn't work

**Comment by gpsaggese** [comment]
> @Sameep2808
> 
> `i docker_build_local_image --version 1.0.0` `i docker_build_local_image --version 1.0.0 --no-cache` when I execute these commands, it's throwing an assertion error.
> 
> ```
> INFO: > cmd='/Users/nitteshkataria/src/venv/amp.client_venv/bin/invoke docker_build_local_image --version 1.0.0 --no-cache'

Did you try to look at the code? If you do, you will find what is the problem.

**Comment by Nitesh703** [comment]
@samarth9008 
upon executing   " /bin/bash -c "source /venv/bin/activate && pip install yfinance" "  this command it throws an error mentioned below.  
'''
user_501@98911dd49352:/app$ /bin/bash -c "source /venv/bin/activate && pip install yfinance"
Collecting yfinance
  Downloading yfinance-0.2.38-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 2.5 MB/s 
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 9.2 MB/s 
Requirement already satisfied: pandas>=1.3.0 in /venv/lib/python3.9/site-packages (from yfinance) (2.1.1)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.4.4-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (116 kB)
     |████████████████████████████████| 116 kB 32.3 MB/s 
Requirement already satisfied: lxml>=4.9.1 in /venv/lib/python3.9/site-packages (from yfinance) (4.9.3)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /venv/lib/python3.9/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: requests>=2.31 in /venv/lib/python3.9/site-packages (from yfinance) (2.31.0)
Collecting appdirs>=1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pytz>=2022.5 in /venv/lib/python3.9/site-packages (from yfinance) (2023.3.post1)
Collecting peewee>=3.16.2
  Downloading peewee-3.17.3.tar.gz (3.0 MB)
     |████████████████████████████████| 3.0 MB 60.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.16.5 in /venv/lib/python3.9/site-packages (from yfinance) (1.26.0)
Requirement already satisfied: six>=1.9 in /venv/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /venv/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: tzdata>=2022.1 in /venv/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /venv/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: soupsieve>1.2 in /venv/lib/python3.9/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /venv/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /venv/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /venv/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2023.7.22)
Requirement already satisfied: urllib3<3,>=1.21.1 in /venv/lib/python3.9/site-packages (from requests>=2.31->yfinance) (1.26.17)
Building wheels for collected packages: peewee
  Building wheel for peewee (PEP 517) ... done
  Created wheel for peewee: filename=peewee-3.17.3-py3-none-any.whl size=138407 sha256=25ef0c4ba90142c2661d89c1a78ca5ad25ca10b737242f53f8dd767bbea6d3e6
  Stored in directory: /home/.cache/pip/wheels/a7/64/49/81f05b55b5fcafe2ea6316aac808b15228715abc3d2632a240
Successfully built peewee
Installing collected packages: html5lib, frozendict, multitasking, appdirs, peewee, yfinance
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/venv/lib/python3.9/site-packages/html5lib-1.1.dist-info'
Consider using the `--user` option or check the permissions.
'''

**Comment by samarth9008** [comment]
Try

```
" /bin/bash -c "source /venv/bin/activate && sudo pip install yfinance"
```

**Comment by samarth9008** [comment]
Its okay for now if its not running. Make sure the docker container works and the unit tests in running

**Comment by Nitesh703** [comment]
@samarth9008 
Ok. Docker container is working & unit tests are also running. 
I'm ready for warm-up issue.

**Comment by Nitesh703** [comment]
Hello @samarth9008 , 
following up on my previous comment, I'm waiting for warm-up issue.

**Comment by samarth9008** [comment]
Assigned https://github.com/kaizen-ai/kaizenflow/issues/979

Closing this now
