### ISSUE TITLE
Create a SOTA baseline

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#997]
We want to implement the DoublePoisson model and the ELO model from http://ida.felk.cvut.cz/zelezny/pubs/MathSport2019a.pdf. It should be a quick and simple baseline.

Do we have all the data needed?
Can we reuse the same baseline we have to reproduce exactly their results?
I think the data is https://osf.io/kqcye/

What is the hit rate?
What are the confidence intervals around it?

FYI @gpsaggese

**Comment by gpsaggese** [comment]
@tkpratardan any ETA for this? Can you pls post a plan?

Our approach is update GH issue once per day + 1 PR per day, it doesn't have to be perfect but show the direction so we can all chime in. If the bug is too big, let's split into pieces (e.g., get the data, do double poisson, etc)

@sonaalKant we also need an Epic (I'd keep the Epics on cmamp side), and complexity.

**Comment by sonaalKant** [comment]
> @sonaalKant we also need an Epic (I'd keep the Epics on cmamp side), and complexity.

Filed an EPIC (before viewing this comment) but on kaizenflow. I will move the EPIC to cmamp.

**Comment by gpsaggese** [comment]
Thanks @sonaalKant. Pls keep supervising @tkpratardan . He has good technical skills, but he needs to become proficient with our way of doing things.
